#!/usr/bin/env bash

# This script contains variables used in all of the other scripts in this directory

# neckbeard bash used to get the value of _this_ directory.
THIS_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

# variables with defaults. these are overridden by our deployment infra in staging and prod
: "${DP_SEC_DB_USER:="postgres"}"
: "${DP_SEC_DB_PASSWORD:="tbd"}"
: "${DP_SEC_DB_HOST:="localhost"}"
: "${DP_SEC_DB_PORT:="5432"}"
: "${DP_SEC_DB_NAME:="mockpfi"}"

# these are exported because they're used by child processes (e.g. dbmate)
export DBMATE_MIGRATIONS_DIR=$THIS_DIR/../migrations
export DATABASE_URL="postgres://$DP_SEC_DB_USER:$DP_SEC_DB_PASSWORD@$DP_SEC_DB_HOST:$DP_SEC_DB_PORT/$DP_SEC_DB_NAME?sslmode=disable"

# colors that can be used in bash scripts when echoing
RED="$(tput bold && tput setaf 1)"
YELLOW="$(tput bold && tput setaf 3)"
RESET="$(tput sgr0)"

_logger() {
	local color="$1"
	local level="$2"
	shift 2

	local message="$*"
	local current_datetime="$(date +'%F %T')"
	printf "%s%s%10s%s%s\n" "$color" "$current_datetime" "$level - " "$message" "$RESET"
}

error() {
	_logger "$RED" "ERROR" "$*"
}

warn() {
	_logger "$YELLOW" "WARN" "$*"
}

info() {
	_logger "$RESET" "INFO" "$*"
}
