#!/usr/bin/env bash

# This script runs db migrations. environment variables can be found in `common`
THIS_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$THIS_DIR/common"

if [ -d "$DBMATE_MIGRATIONS_DIR" ]; then
	if [ -z "$(command ls -A1 "$DBMATE_MIGRATIONS_DIR")" ]; then
		info "No migrations found."
		exit 0
	fi

	info "Running migrations for postgres://$DP_SEC_DB_USER:****@$DP_SEC_DB_HOST:$DP_SEC_DB_PORT/$DP_SEC_DB_NAME?sslmode=disable"
	if dbmate --wait --wait-timeout=60s up; then
		info "Migrations completed successfully."
	else
		error "Migrations failed."
	fi
fi
