#!/usr/bin/env bash

# this script starts dockerized mysql if it isn't already running.

THIS_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$THIS_DIR/common"
source "$THIS_DIR/local"

if [ -n "$RUNNING_CONTAINER" ]; then
	echo "Container $CONTAINER_NAME is already running"
elif [ -n "$STOPPED_CONTAINER" ]; then
	echo "Starting $CONTAINER_NAME"
	docker start $CONTAINER_NAME
else
	echo "Creating & starting $CONTAINER_NAME"
	docker run --detach \
		--name "$CONTAINER_NAME" \
		--env "POSTGRES_USER=$DP_SEC_DB_USER" \
		--env "POSTGRES_DB=$DP_SEC_DB_NAME" \
		--env "POSTGRES_PASSWORD=$DP_SEC_DB_PASSWORD" \
		--env "PGSSLMODE=disable" \
		--publish "$DP_SEC_DB_PORT:5432" \
		postgres:15.4
fi
