#!/usr/bin/env bash

# This script drops you into a mysql shell.

THIS_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$THIS_DIR/common"
source "$THIS_DIR/local"

if [ -n "$RUNNING_CONTAINER" ]; then
	echo "Using $CONTAINER_NAME"
	docker exec --interactive --tty "$CONTAINER_NAME" psql --username "$DP_SEC_DB_USER"
else
	echo "$CONTAINER_NAME is not currently running, use the start-pg command first"
fi
